apply plugin: 'java'
apply plugin: 'idea'

description = 'JMBE Audio Library build script'

subprojects {
    apply plugin: 'java'
    version = '2.0.0'

    java {
        sourceCompatibility = JavaVersion.VERSION_17
    }
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
