package analysis;

import java.nio.file.*;

/**
 * Converts a trained MLP2 model file into a self-contained Java class holding the weights, so the decoder needs no
 * model file at run time.
 *
 *   java ModelToJava gain-model.txt LearnedEnhancerModel.java [packageName]
 *
 * The weights are stored as one text block that is parsed when the class loads (this avoids the JVM's 64 KB method
 * limit). Use:  LearnedEnhancer.Mlp net = LearnedEnhancerModel.create();
 */
public final class ModelToJava {
    public static void main(String[] a) throws Exception {
        if (a.length < 2) { System.err.println("usage: ModelToJava model.txt LearnedEnhancerModel.java [package]"); return; }
        String text = Files.readString(Paths.get(a[0]));
        LearnedEnhancer.Mlp.load(Paths.get(a[0]));                       // validates the file before embedding it
        String[] lines = text.trim().split("\\R");
        StringBuilder sb = new StringBuilder();
        if (a.length > 2) sb.append("package ").append(a[2]).append(";\n\n");
        sb.append("import java.io.IOException;\n\n");
        sb.append("/** Generated by ModelToJava from ").append(Paths.get(a[0]).getFileName()).append(". Do not edit. */\n");
        sb.append("public final class LearnedEnhancerModel {\n");
        sb.append("    private static final String[] DATA = {\n");
        for (String l : lines) sb.append("        \"").append(l.trim()).append("\",\n");
        sb.append("    };\n\n");
        sb.append("    private LearnedEnhancerModel() {}\n\n");
        sb.append("    public static LearnedEnhancer.Mlp create() {\n");
        sb.append("        try {\n");
        sb.append("            return LearnedEnhancer.Mlp.parse(String.join(\"\\n\", DATA));\n");
        sb.append("        } catch (IOException e) {\n");
        sb.append("            throw new IllegalStateException(e);\n");
        sb.append("        }\n");
        sb.append("    }\n}\n");
        Path outp = Paths.get(a[1]).toAbsolutePath(); Files.createDirectories(outp.getParent()); Files.writeString(outp, sb.toString());
        System.out.println("wrote " + a[1] + " (" + lines.length + " lines of weights)");
    }
}
